baseurl = "https://www.latampodcast.com"
title = "Latam Podcast"
author = ""
canonifyurls = true
paginate = 3
theme = "aether"

[params]
brand = "LatamPodcast"
description = "Mejores Podcast Latinoamericanos"
bgimg = "img/ignasi_pattern_s.png"
