# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: latampodcast_development
  pool: 5

staging:
  <<: *default
  development:
  adapter: postgresql
  encoding: unicode
  database: latampodcast_staging
  pool: 5

production:
  <<: *default
  development:
  adapter: postgresql
  encoding: unicode
  database: latampodcast_production
  pool: 5
